# Generated by Django 6.1 on 2026-09-10 07:40

from django.db import migrations, models

# 0022 creo envios_correo mediante RunSQL. Registrar ahora el modelo en el
# estado de Django: managed=False hace esta operacion un no-op en la BD.


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_videos_s3'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('plantilla', models.CharField(max_length=60)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('entidad', models.CharField(blank=True, max_length=60, null=True)),
                ('entidad_id', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('numero_intento', models.SmallIntegerField(default=1)),
                ('proveedor_id', models.CharField(blank=True, max_length=180, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'envios_correo',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
