# Generated by Django 6.1 on 2026-09-12 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_enviocorreo_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True, max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
                ('duracion_estimada', models.PositiveIntegerField(default=0, help_text='Duracion en segundos.')),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_impartidos', to='core.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField(default=0, help_text='Duracion en segundos.')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='core.curso')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecciones', to='core.video')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visto', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='core.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_lecciones', to='core.usuario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_certificado', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.BinaryField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_cursos', to='core.usuario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.curso')),
            ],
            options={
                'ordering': ['-fecha_emision', 'id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'curso'), name='certificado_usuario_curso_unico')],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False, editable=False)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_cursos', to='core.usuario')),
            ],
            options={
                'ordering': ['-fecha_inscripcion', 'id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'curso'), name='usuario_curso_unico'), models.CheckConstraint(condition=models.Q(('porcentaje_avance__gte', 0), ('porcentaje_avance__lte', 100)), name='avance_entre_0_y_100')],
            },
        ),
        migrations.AddConstraint(
            model_name='leccion',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='curso_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='progresoleccion',
            constraint=models.UniqueConstraint(fields=('usuario', 'leccion'), name='usuario_leccion_unico'),
        ),
    ]
