# Generated by Django 6.1 on 2026-09-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_permisos_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
