# Generated by Django 6.1 on 2026-10-01 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cursos_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuerpo', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_edicion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='core.usuario')),
            ],
            options={
                'ordering': ['-fecha_publicacion', '-id'],
            },
        ),
    ]
