# Generated by Django 6.1 on 2026-10-01 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_permiso_publicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuerpo', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='core.usuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.publicacion')),
            ],
            options={
                'ordering': ['fecha_publicacion', 'id'],
                'indexes': [models.Index(fields=['publicacion', 'fecha_publicacion'], name='core_coment_publica_fa2412_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='core.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='core.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publicacion', 'usuario'), name='reaccion_publicacion_usuario_unica')],
            },
        ),
    ]
