# Generated by Django 6.1 on 2026-10-01 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_desactivar_claves_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('spam', 'Spam o publicidad'), ('acoso', 'Acoso u ofensas'), ('suplantacion', 'Suplantación de identidad'), ('inapropiado', 'Contenido inapropiado'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=500)),
                ('cuerpo_reportado', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('eliminado', 'Contenido eliminado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('autor_reportado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_recibidos', to='core.usuario')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='core.comentario')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='core.publicacion')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_hechos', to='core.usuario')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to='core.usuario')),
            ],
            options={
                'ordering': ['creado_en', 'id'],
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='core_report_estado_4cef5e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente'), ('publicacion__isnull', False)), fields=('reportado_por', 'publicacion'), name='reporte_publicacion_pendiente_unico'), models.UniqueConstraint(condition=models.Q(('comentario__isnull', False), ('estado', 'pendiente')), fields=('reportado_por', 'comentario'), name='reporte_comentario_pendiente_unico')],
            },
        ),
    ]
