# Generated by Django 6.1 on 2026-10-02 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_cache_compartida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoPublicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('content_type', models.CharField(max_length=50)),
                ('s3_key', models.CharField(editable=False, max_length=512, unique=True)),
                ('tamano', models.PositiveBigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_publicacion', to='core.usuario')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='core.publicacion')),
            ],
            options={
                'ordering': ['orden', 'creado_en'],
                'indexes': [models.Index(fields=['publicacion', 'orden'], name='core_adjunt_publica_bd7299_idx')],
            },
        ),
    ]
