# Generated by Django 6.1 on 2026-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_adjuntos_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_clave',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
