# Generated by Django 6.1.1 on 2026-10-09 17:21

import django.db.models.deletion
from django.db import migrations, models


ETAPA_INICIAL = "Postulación recibida"


def sembrar_historial(apps, schema_editor):
    """
    Historial de arranque para las postulaciones que ya existían.

    No hay registro de los pasos intermedios —la tabla sólo guardaba el
    estado vigente—, así que se reconstruye lo que sí se sabe: la recepción
    en `registrada_en` y, si la postulación ya se movió, su estado actual en
    `ultima_actividad_en`. Una línea de tiempo vacía diría que nunca pasó
    nada, que es falso.
    """
    Postulacion = apps.get_model("core", "Postulacion")
    EventoPostulacion = apps.get_model("core", "EventoPostulacion")

    eventos = []
    for postulacion in Postulacion.objects.all().iterator():
        eventos.append(
            EventoPostulacion(
                postulacion_id=postulacion.id,
                estado="nuevo",
                etapa=ETAPA_INICIAL,
                progreso=0,
                ocurrido_en=postulacion.registrada_en,
            )
        )

        sigue_al_inicio = (
            postulacion.estado == "nuevo"
            and postulacion.etapa == ETAPA_INICIAL
            and postulacion.progreso == 0
        )
        if sigue_al_inicio:
            continue

        eventos.append(
            EventoPostulacion(
                postulacion_id=postulacion.id,
                estado=postulacion.estado,
                etapa=postulacion.etapa,
                progreso=postulacion.progreso,
                # Nunca antes de la recepción, aunque los datos sembrados
                # traigan las fechas al revés.
                ocurrido_en=max(
                    postulacion.ultima_actividad_en, postulacion.registrada_en
                ),
            )
        )

    EventoPostulacion.objects.bulk_create(eventos, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_portada_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPostulacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('revision', 'Revisión'), ('shortlist', 'Lista corta'), ('rechazado', 'Rechazado'), ('contratado', 'Contratado')], max_length=20)),
                ('etapa', models.CharField(max_length=120)),
                ('progreso', models.SmallIntegerField()),
                ('ocurrido_en', models.DateTimeField()),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.postulacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_postulacion', to='core.usuario')),
            ],
            options={
                'ordering': ['ocurrido_en', 'id'],
                'indexes': [models.Index(fields=['postulacion', 'ocurrido_en'], name='core_evento_postula_34844d_idx')],
            },
        ),
        migrations.RunPython(sembrar_historial, migrations.RunPython.noop),
    ]
