# Generated by Django 6.1.1 on 2026-10-09 18:19

from django.db import migrations, models


# `postulaciones.estado` es un ENUM de Postgres creado por database/schema.sql,
# así que el estado nuevo hay que agregarlo al tipo, no sólo a los choices.
#
# IF NOT EXISTS porque schema.sql ya lo trae para las bases nuevas: ahí la
# migración 0001 crea el tipo completo y esto no hace nada.
#
# Postgres no sabe quitar un valor de un ENUM sin recrear el tipo y todas las
# columnas que lo usan, así que no hay reversa: el valor sobrante es inocuo.
AGREGAR_RETIRADA_SQL = (
    "ALTER TYPE estado_postulacion ADD VALUE IF NOT EXISTS 'retirada';"
)


class Migration(migrations.Migration):

    # ADD VALUE no se puede usar en la misma transacción que lo agrega; fuera
    # de un bloque atómico, el valor queda confirmado al terminar la sentencia.
    atomic = False

    dependencies = [
        ('core', '0039_eventos_postulacion'),
    ]

    operations = [
        migrations.RunSQL(AGREGAR_RETIRADA_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='eventopostulacion',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('revision', 'Revisión'), ('shortlist', 'Lista corta'), ('rechazado', 'Rechazado'), ('contratado', 'Contratado'), ('retirada', 'Retirada')], max_length=20),
        ),
    ]
