"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
import warnings
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers as cors_default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATABASE_SQL_DIR = BASE_DIR / 'database'

# Configuración local de PayPal. Las variables definidas por el sistema tienen
# prioridad y el archivo permanece fuera de Git mediante `.env.*`.
load_dotenv(BASE_DIR / '.env.paypal', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(nombre, default=False):
    return os.getenv(nombre, str(default)).strip().lower() in {
        "1", "true", "yes", "on",
    }


# En una demo local se genera una clave efimera si aun no se configuro una.
# Reiniciar el servidor invalida sus JWT, lo cual hace visible la omision sin
# conservar una clave publica en Git. Fuera de DEBUG la clave es obligatoria.
DEBUG = env_bool("DJANGO_DEBUG", True)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError("Falta DJANGO_SECRET_KEY en un entorno sin DEBUG.")
    SECRET_KEY = secrets.token_urlsafe(64)
    warnings.warn(
        "DJANGO_SECRET_KEY no esta configurada; los tokens se invalidaran "
        "al reiniciar el servidor.",
        RuntimeWarning,
    )

# Hosts permitidos, separados por comas. Vacio y con DEBUG=True Django ya
# acepta localhost, que es el caso normal; la variable existe para los tuneles
# de desarrollo (cloudflared, ngrok), cuyo dominio cambia en cada reinicio y
# no tiene por que quedar escrito en el codigo. Un punto inicial vale como
# comodin de subdominio: `.trycloudflare.com`.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    "rest_framework",
    "corsheaders",
    "drf_yasg",

    # Aplicaciones del proyecto
    "core",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'DJ_try'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Los reportes psicometricos son documentos privados. MEDIA_ROOT se usa como
# almacenamiento local durante esta etapa, pero no se publica mediante urls.py.
MEDIA_ROOT = Path(os.getenv('PRIVATE_MEDIA_ROOT', BASE_DIR / 'media'))
REPORTE_PSICOMETRICO_PRECIO = os.getenv('REPORTE_PSICOMETRICO_PRECIO', '499.00')
REPORTE_PSICOMETRICO_MONEDA = os.getenv('REPORTE_PSICOMETRICO_MONEDA', 'MXN')
REPORTE_PSICOMETRICO_MAX_MB = int(
    os.getenv('REPORTE_PSICOMETRICO_MAX_MB', '10')
)

# PayPal REST API. El secreto nunca se expone al frontend ni se guarda en BD.
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox').lower()
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')
PAYPAL_API_BASE_URL = (
    'https://api-m.paypal.com'
    if PAYPAL_MODE == 'live'
    else 'https://api-m.sandbox.paypal.com'
)
PAYPAL_RETURN_URL = os.getenv(
    'PAYPAL_RETURN_URL', 'http://localhost:5173/pagos/paypal/return'
)
PAYPAL_CANCEL_URL = os.getenv(
    'PAYPAL_CANCEL_URL', 'http://localhost:5173/pagos/paypal/cancel'
)
# Id del webhook dado de alta en el panel de PayPal. Sin el no se puede
# comprobar la firma de un evento, y un evento sin comprobar no se procesa:
# el endpoint es publico y cualquiera podria anunciar un cobro que no existe.
PAYPAL_WEBHOOK_ID = os.getenv('PAYPAL_WEBHOOK_ID', '')
PAYPAL_HTTP_TIMEOUT = float(os.getenv('PAYPAL_HTTP_TIMEOUT', '15'))
PAYPAL_PENDING_TIMEOUT_MINUTES = int(
    os.getenv('PAYPAL_PENDING_TIMEOUT_MINUTES', '5')
)
PAYPAL_ORDER_TTL_HOURS = int(os.getenv('PAYPAL_ORDER_TTL_HOURS', '3'))


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.api.authentication.UsuarioJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_LOGIN', '5/minute'),
        'registro': os.getenv('THROTTLE_REGISTRO', '5/hour'),
        'refresh': os.getenv('THROTTLE_REFRESH', '30/minute'),
        'paypal_webhook': os.getenv('THROTTLE_PAYPAL_WEBHOOK', '120/minute'),
    },
}

# Django corta cuerpos no basados en archivos antes de que ocupen memoria sin
# limite. Los PDFs usan el manejo de uploads y conservan su propio maximo.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(1024 * 1024))
)

# Se dejan explicitas para que `manage.py check --deploy` detecte si faltan al
# preparar staging/produccion, sin romper el desarrollo HTTP local.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', False)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS', False
)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES', '15'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS', '7'))
    ),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Documentacion OpenAPI (drf-yasg)
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Escribe: Bearer <token_de_acceso>',
        },
    },
    'USE_SESSION_AUTH': False,
}


# El checkout manda `Idempotency-Key` para que dos envios de la misma compra
# no abran dos ordenes. No esta en la lista por defecto de django-cors-headers,
# y sin declararla el navegador aprueba el preflight pero se niega a mandar el
# POST: en el servidor no queda ni rastro, y en la pagina sale un
# "failed to fetch" que no dice de que.
CORS_ALLOW_HEADERS = (*cors_default_headers, 'idempotency-key')

# Frontends permitidos durante el desarrollo local
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://localhost:5173',
    ).split(',')
    if origin.strip()
]
